### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by MHT417** [ThePedroo/Coglink#3]
I would like to propose a feature regarding channel controls. Specifically, if there are several bots operating on separate channels, the feature should determine if the user-requested music plays exclusively on the channel to which the user is connected and does not play the same song in every voice chat.

**Comment by ThePedroo** [comment]
Landed on https://github.com/PerformanC/Coglink/commit/b159f03bff92974865b7f9496e2d65e3b4181a61.
